# A short, descriptive name of this building block collection
name: CHEK Project profiles

# Short abstract for this collection (optional)
abstract: |
  Profiles for the CHEK project as Building Blocks.

# Description for this collection (optional)
description: |
  This register contains CHEK DBP project data requirements profiles as building blocks.
  
  For a building block to be a valid CHEK profile, it needs to:
  
    1. Have a `data.ttl` file with the RDF description of the profile (using [The Profiles Vocabulary](https://www.w3.org/TR/dx-prof/))  
    2. Contain some [SHACL shapes](https://ogcincubator.github.io/bblocks-docs/create/validation#shacl-validation)
    3. Have the `chek-validation-profile` tag
  
  You can use the [dummy profile](https://ogcincubator.github.io/chek-profiles-bblocks/bblock/ogc.chekdbp.profiles.common.dummy)
  as a template.
  
  Profile dependencies can be declared either by using `dependsOn` in `bblock.json` (with the id of the bblock), or using
  [`prof:isProfileOf`](https://www.w3.org/TR/dx-prof/#Property:isProfileOf) in the RDF definition of the profile.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.chekdbp.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
