$schema: https://json-schema.org/draft/2020-12/schema

type: object
allOf:
  - $ref: ../base-rule/schema.yaml

  - required:
      - objectSelector
    properties:
      objectSelector:
        $ref: ../object-selector/schema.yaml
