$schema: https://json-schema.org/draft/2020-12/schema

type: object
required:
  - id
properties:
  id:
    description: Identifier for this rule, a URI preferably
    type: string
  title:
    description: Title for this rule
    type: string
  description:
    description: Textual description for this rule
    type: string
  message:
    description: Message returned by the SHACL validator
    type: string
